/**
 * Generate a pi extension that enforces a ToolPolicy at runtime.
 *
 * The generated extension is a self-contained TypeScript module that:
 *   - Imports `ExtensionAPI` and `isToolCallEventType` from pi
 *   - Inlines the policy as a constant
 *   - On `tool_call`, runs `checkPolicy()` and returns `{block:true}` if denied
 *   - On `tool_result`, runs `redactContent()` to scrub sensitive patterns
 *   - Uses `ctx.ui.confirm()` for tools in `requireApproval`
 *
 * Generated to `~/.pilot/extensions/pilot-policy-<name>.ts`. Pi auto-loads
 * from this directory on startup.
 *
 * Why generate code instead of shipping a generic extension that reads
 * a policy file at runtime? Two reasons:
 *   1. Pi extensions are loaded by jiti — they need to be valid TypeScript
 *      at load time. Embedding the policy avoids an extra fs round-trip.
 *   2. Generated code is reviewable: users can `cat` the extension file
 *      and see exactly what gets enforced.
 *
 * See: docs/roadmap-pi-grounded.md (Layer 2 policy section).
 */

import type { ToolPolicy } from "./policy.js";

/**
 * Generate the source code of a policy-enforcing extension.
 * The result is valid TypeScript that pi can load via jiti.
 */
export function generatePolicyExtension(policy: ToolPolicy): string {
  // Serialize the policy as inline JSON inside the generated code.
  // The generated extension has zero runtime deps on Pilot — it only
  // depends on `@earendil-works/pi-coding-agent` and `node:` builtins.
  //
  // We add `: { ... }` to widen the literal type so the generated
  // code can treat the arrays as `string[]` (otherwise TS infers
  // tuple literals like `readonly ["bash"]` which break `.includes()`).
  const policyJson = JSON.stringify(
    {
      name: policy.name,
      allow: policy.allow,
      deny: policy.deny,
      denyPaths: policy.denyPaths,
      denyCommands: policy.denyCommands,
      sensitivePatterns: policy.sensitivePatterns,
      requireApproval: policy.requireApproval,
    },
    null,
    2,
  );

  return `// GENERATED by Pilot v0.4.3 — DO NOT EDIT BY HAND
// To regenerate, run: pilot policy apply ${policy.name}
// Policy file: ~/.pilot/policy/${policy.name}.toml
//
// This extension enforces a ToolPolicy declared in Pilot. It is
// auto-loaded by pi from ~/.pilot/extensions/ on every session.
//
// To temporarily disable, move this file out of the extensions dir
// and run /reload in pi.

import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";

const POLICY: {
  name: string;
  allow: string[];
  deny: string[];
  denyPaths: string[];
  denyCommands: string[];
  sensitivePatterns: string[];
  requireApproval: string[];
} = ${policyJson};

// ─── Path matcher (generated) ─────────────────────────────────

function matchPath(pattern: string, target: string): boolean {
  const p = pattern.replace(/^\\/+/, "");
  const t = target.replace(/^\\/+/, "");
  let re = "";
  let i = 0;
  while (i < p.length) {
    if (p[i] === "*" && p[i + 1] === "*") {
      re += ".*";
      i += 2;
      if (p[i] === "/") i++;
    } else if (p[i] === "*") {
      re += "[^/]*";
      i++;
    } else if (/[.+^$(){}|\\\\?[\]]/.test(p[i]!)) {
      re += "\\\\" + p[i];
      i++;
    } else {
      re += p[i];
      i++;
    }
  }
  return new RegExp("^" + re + "$").test(t);
}

// ─── Redact (generated) ───────────────────────────────────────

function redactContent(content: unknown): unknown {
  if (typeof content !== "string") return content;
  if (POLICY.sensitivePatterns.length === 0) return content;
  let out = content;
  for (const pat of POLICY.sensitivePatterns) {
    if (pat.length === 0) continue;
    try {
      out = out.replace(new RegExp(pat, "g"), "[REDACTED]");
    } catch {
      out = out.split(pat).join("[REDACTED]");
    }
  }
  return out;
}

// ─── Tool call gate ───────────────────────────────────────────

interface PolicyResult {
  block: boolean;
  reason?: string;
  requireApproval?: boolean;
}

function checkCall(name: string, input: unknown): PolicyResult {
  const args = (input ?? {}) as Record<string, unknown>;

  if (POLICY.deny.includes(name)) {
    return {
      block: true,
      reason: \`tool "\${name}" denied by policy "\${POLICY.name}"\`,
    };
  }
  if (POLICY.allow.length > 0 && !POLICY.allow.includes(name)) {
    return {
      block: true,
      reason: \`tool "\${name}" not in allow list of policy "\${POLICY.name}"\`,
    };
  }
  if (POLICY.requireApproval.includes(name)) {
    return { block: false, requireApproval: true };
  }
  if (name === "read" || name === "edit" || name === "write") {
    const path = (args.path ?? args.file_path) as string | undefined;
    if (path) {
      for (const pattern of POLICY.denyPaths) {
        if (matchPath(pattern, path)) {
          return {
            block: true,
            reason: \`path "\${path}" matches denied glob "\${pattern}" in policy "\${POLICY.name}"\`,
          };
        }
      }
    }
  }
  if (name === "bash") {
    const command = args.command as string | undefined;
    if (command) {
      for (const pat of POLICY.denyCommands) {
        try {
          if (new RegExp(pat).test(command)) {
            return {
              block: true,
              reason: \`command matches denied regex "\${pat}" in policy "\${POLICY.name}"\`,
            };
          }
        } catch {
          /* skip invalid */
        }
      }
    }
  }
  return { block: false };
}

// ─── Extension entry point ────────────────────────────────────

export default function (pi: ExtensionAPI): void {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  (pi.on as any)("tool_call", async (event: { toolName: string; input: unknown }, ctx: { ui: { notify: (m: string, l: string) => void; confirm: (t: string, m: string) => Promise<boolean> } }) => {
    const result = checkCall(event.toolName, event.input);
    if (result.block) {
      ctx.ui.notify(\`[pilot] \${result.reason}\`, "error");
      return { block: true, reason: result.reason };
    }
    if (result.requireApproval) {
      const ok = await ctx.ui.confirm(
        "Pilot policy approval required",
        \`Policy "\${POLICY.name}" wants you to confirm: \${event.toolName}\`,
      );
      if (!ok) {
        return { block: true, reason: "User denied approval" };
      }
    }
    return;
  });

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  (pi.on as any)("tool_result", async (event: { content?: unknown[] }) => {
    if (!Array.isArray(event.content)) return;
    let changed = false;
    const next = event.content.map((block: unknown) => {
      if (
        block &&
        typeof block === "object" &&
        (block as { type?: string }).type === "text" &&
        typeof (block as { text?: unknown }).text === "string"
      ) {
        const redacted = redactContent(
          (block as { text: string }).text,
        );
        if (redacted !== (block as { text: string }).text) {
          changed = true;
          return { ...(block as object), text: redacted as string };
        }
      }
      return block;
    });
    if (changed) {
      return { content: next };
    }
    return;
  });
}
`;
}
