/**
 * Tests for `commands/agent.ts` (v0.5.4 Co-pilot entrypoint).
 *
 * `run()` spawns pi as a child process — that's an integration
 * concern. We only unit-test the option parser here, which is the
 * deterministic part. The spawn behavior is covered by the manual
 * smoke test (`npm run build && pilot agent`) and by the installer
 * tests (which exercise the symlink dance the agent command triggers).
 */

import { describe, it, expect } from "vitest";
import { parseOptions } from "../../src/commands/agent.js";

describe("agent: parseOptions", () => {
  it("returns sensible defaults when no args", () => {
    const opt = parseOptions([]);
    expect(opt.noExtension).toBe(false);
    expect(opt.printServer).toBe(true);
    expect(opt.cwd).toBeUndefined();
    expect(opt.profile).toBeUndefined();
    expect(opt.model).toBeUndefined();
    expect(opt.passthrough).toEqual([]);
  });

  it("parses --cwd", () => {
    const opt = parseOptions(["--cwd", "/tmp/proj"]);
    expect(opt.cwd).toBe("/tmp/proj");
  });

  it("parses --profile", () => {
    const opt = parseOptions(["--profile", "pi-architect"]);
    expect(opt.profile).toBe("pi-architect");
  });

  it("parses --model", () => {
    const opt = parseOptions(["--model", "claude-opus-4-6"]);
    expect(opt.model).toBe("claude-opus-4-6");
  });

  it("parses --no-extension", () => {
    const opt = parseOptions(["--no-extension"]);
    expect(opt.noExtension).toBe(true);
  });

  it("parses --no-print-server", () => {
    const opt = parseOptions(["--no-print-server"]);
    expect(opt.printServer).toBe(false);
  });

  it("splits own args from `--` passthrough", () => {
    const opt = parseOptions([
      "--cwd",
      "/tmp/proj",
      "--",
      "-p",
      "hello",
      "--session-dir",
      "/tmp/sess",
    ]);
    expect(opt.cwd).toBe("/tmp/proj");
    expect(opt.passthrough).toEqual([
      "-p",
      "hello",
      "--session-dir",
      "/tmp/sess",
    ]);
  });

  it("accepts multiple own flags in any order", () => {
    const opt = parseOptions([
      "--model",
      "claude-sonnet-4-5",
      "--profile",
      "pi-architect",
      "--no-print-server",
    ]);
    expect(opt.model).toBe("claude-sonnet-4-5");
    expect(opt.profile).toBe("pi-architect");
    expect(opt.printServer).toBe(false);
  });

  it("ignores unknown flags (passed to pi before --)", () => {
    const opt = parseOptions(["--cwd", "/tmp/proj", "--some-pi-flag", "foo"]);
    expect(opt.cwd).toBe("/tmp/proj");
    // Unknown flag didn't crash anything; it just wasn't consumed.
  });
});

describe("pilot-tools extension file (v0.5.4 deliverable)", () => {
  /**
   * Sanity checks on the actual shipped extension file. These are
   * belt-and-suspenders: the file lives in src/extensions/ and gets
   * copied to dist/extensions/ on build. We verify both paths have
   * the same content and that the file exports a default function.
   */
  it("exists at src/extensions/pilot-tools.ts and in dist/extensions/", async () => {
    const fs = await import("node:fs");
    const path = await import("node:path");
    const srcFile = path.resolve(
      path.dirname(new URL(import.meta.url).pathname),
      "../../src/extensions/pilot-tools.ts",
    );
    expect(fs.existsSync(srcFile)).toBe(true);

    // dist version is generated by the build step; skip if absent
    // (e.g. during a clean checkout before `npm run build`).
    const distFile = path.resolve(
      path.dirname(new URL(import.meta.url).pathname),
      "../../dist/extensions/pilot-tools.ts",
    );
    if (fs.existsSync(distFile)) {
      const src = fs.readFileSync(srcFile, "utf-8");
      const dist = fs.readFileSync(distFile, "utf-8");
      expect(dist).toBe(src);
    }
  });

  it("exports a default function", async () => {
    const fs = await import("node:fs");
    const path = await import("node:path");
    const srcFile = path.resolve(
      path.dirname(new URL(import.meta.url).pathname),
      "../../src/extensions/pilot-tools.ts",
    );
    const content = fs.readFileSync(srcFile, "utf-8");
    // Default function exported.
    expect(content).toMatch(/export default function pilotToolsExtension/);
    // Registers the most important tools — at minimum: install, profile,
    // session search, doctor. If a tool gets renamed/removed in the
    // future, this test should be updated intentionally.
    expect(content).toMatch(/pilot_pack_install/);
    expect(content).toMatch(/pilot_profile_activate/);
    expect(content).toMatch(/pilot_session_search/);
    expect(content).toMatch(/pilot_doctor/);
  });
});
