/**
 * Tests for `core/policy-extension.ts` — generated extension source.
 *
 * The generated code must:
 *   1. Be parseable as TypeScript (we use tsc to verify)
 *   2. Inlude the policy data as a const
 *   3. Wire up `tool_call` and `tool_result` handlers
 *   4. Reference `ExtensionAPI` from pi
 */

import { describe, it, expect } from "vitest";
import { generatePolicyExtension } from "../../src/core/policy-extension.js";
import type { ToolPolicy } from "../../src/core/policy.js";
import { execSync } from "node:child_process";
import { writeFileSync, mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

function makePolicy(overrides: Partial<ToolPolicy> = {}): ToolPolicy {
  return {
    name: "safe-bash",
    description: "Safe defaults",
    allow: [],
    deny: ["bash"],
    denyPaths: ["**/.env"],
    denyCommands: ["^rm\\s+-rf\\s+/"],
    sensitivePatterns: ["sk-[A-Za-z0-9]+"],
    requireApproval: ["write"],
    createdAt: "2026-07-03T00:00:00.000Z",
    updatedAt: "2026-07-03T00:00:00.000Z",
    ...overrides,
  };
}

describe("generatePolicyExtension — surface checks", () => {
  it("includes a GENERATED banner", () => {
    const src = generatePolicyExtension(makePolicy());
    expect(src).toMatch(/GENERATED by Pilot/);
  });
  it("includes the policy name in a comment", () => {
    const src = generatePolicyExtension(makePolicy({ name: "my-name" }));
    expect(src).toMatch(/Policy file:.*my-name\.toml/);
  });
  it("embeds the policy as a const", () => {
    const src = generatePolicyExtension(makePolicy({ name: "x" }));
    expect(src).toMatch(/const POLICY:/);
    expect(src).toMatch(/"name":\s*"x"/);
  });
  it("imports ExtensionAPI from pi", () => {
    const src = generatePolicyExtension(makePolicy());
    expect(src).toMatch(
      /import\s+type\s*\{\s*ExtensionAPI\s*\}\s*from\s*"@earendil-works\/pi-coding-agent"/,
    );
  });
  it("registers tool_call handler", () => {
    const src = generatePolicyExtension(makePolicy());
    expect(src).toMatch(/"tool_call"/);
  });
  it("registers tool_result handler", () => {
    const src = generatePolicyExtension(makePolicy());
    expect(src).toMatch(/"tool_result"/);
  });
  it("embeds deny list as JSON array", () => {
    const src = generatePolicyExtension(
      makePolicy({ deny: ["bash", "write"] }),
    );
    expect(src).toMatch(/"deny":\s*\[\s*"bash",\s*"write"\s*\]/);
  });
  it("embeds denyPaths as JSON array", () => {
    const src = generatePolicyExtension(
      makePolicy({ denyPaths: ["**/.env", "/etc/**"] }),
    );
    expect(src).toMatch(
      /"denyPaths":\s*\[\s*"\*\*\/\.env",\s*"\/etc\/\*\*"\s*\]/,
    );
  });
});

describe("generatePolicyExtension — TypeScript validity", () => {
  it("compiles cleanly with tsc --noEmit (under pilot's node_modules)", () => {
    const src = generatePolicyExtension(makePolicy());
    // Write to a temp file INSIDE pilot's tree so it can resolve
    // @earendil-works/pi-coding-agent via node_modules.
    const dir = mkdtempSync(join(process.cwd(), ".tmp-ext-"));
    const file = join(dir, "policy.ts");
    writeFileSync(file, src, "utf-8");
    try {
      try {
        execSync(
          `npx tsc --noEmit --strict --skipLibCheck --target es2022 --module nodenext --moduleResolution nodenext ${file}`,
          { cwd: process.cwd(), stdio: "pipe" },
        );
      } catch (e) {
        const err = e as { stdout?: Buffer; stderr?: Buffer };
        throw new Error(
          `tsc failed:\n${err.stdout?.toString() ?? ""}${err.stderr?.toString() ?? ""}`,
        );
      }
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });
});
