/**
 * <HubCapabilityRow> — v1.0.2: one row in the Hub capability list.
 *
 * Renders a single `Capability` (the locally absorbed kind,
 * different from `Pack` which is the npm kind). Capabilities
 * are read-only in v1.0.2 — there's no "remove a capability"
 * because they're generated by `forge absorb` and live in
 * `~/.pilot/capabilities/`. v1.0.2.1 will add a "view source"
 * link to the originating pack.
 *
 * `Capability` shape (see `web/src/lib/types.ts`):
 *   { id, name, description?, level?, sourcePack? }
 */
import { renderT, type Locale } from "@/lib/i18n";
import type { Capability } from "@/lib/types";

export function HubCapabilityRow({
  cap,
  locale,
}: {
  cap: Capability;
  locale: Locale;
}) {
  // Capability shape (see web/src/lib/types.ts):
  //   { id, title, description?, type?, sources, artifacts, ... }
  // `sources` is the originating pack(s) — we show the first
  // source ref as the "from" tag.
  const firstSource = cap.sources?.[0]?.ref;

  return (
    <div className="hub-row hub-row--capability">
      <div className="hub-row-main">
        <div className="hub-row-name">
          {cap.title}
          {cap.type && (
            <span className="hub-pill hub-pill--info">
              {cap.type}
            </span>
          )}
        </div>
        {cap.description && (
          <div className="hub-row-desc">{cap.description}</div>
        )}
        <div className="hub-row-meta">
          {firstSource && (
            <span className="hub-row-meta-item hub-row-meta-mono">
              {firstSource}
            </span>
          )}
        </div>
      </div>
      <div className="hub-row-actions">
        <a
          href={`/capabilities/${encodeURIComponent(cap.id)}`}
          className="hub-btn hub-btn--ghost"
        >
          {renderT(locale, "hub.action.view")}
        </a>
      </div>
    </div>
  );
}
